# Generated by Django 2.2.1 on 2019-05-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user_name',
        ),
    ]
