# Generated by Django 2.2.1 on 2019-05-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190501_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pf_image',
            new_name='pfimage',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='username',
        ),
    ]
